#!/usr/bin/env python3
import sys, time
BLUE='\033[38;5;81m'; GREEN='\033[38;5;114m'; YELLOW='\033[38;5;228m'; DIM='\033[38;5;245m'; BOLD='\033[1m'; RESET='\033[0m'
def out(s='', delay=0.8):
    print(s, flush=True); time.sleep(delay)
def ask_prompt():
    sys.stdout.write(f"\n{BLUE}pi>{RESET} "); sys.stdout.flush()
    return sys.stdin.readline().rstrip('\n')
def main():
    print('\033[2J\033[H', end='')
    out(f"{BOLD}{BLUE}pi-plan-mode{RESET}", 0.4)
    out(f"{DIM}A realistic plan-mode session{RESET}\n", 1.0)
    out(f"{GREEN}Pi{RESET}  Plan mode is available. Use {BOLD}/plan <task>{RESET} to draft before editing.", 0.8)
    ask_prompt()
    out(f"{GREEN}Pi{RESET}  PLAN mode enabled. I’ll inspect the project first, then draft a plan before any edits.", 1.0)
    out(f"{DIM}tool: read package.json{RESET}", .55)
    out(f"{DIM}tool: read src/routes/billing.ts{RESET}", .55)
    out(f"{DIM}tool: bash rg stripe subscription billing src test{RESET}", .8)
    out(f"{GREEN}Pi{RESET}  One choice changes the implementation.\n", .7)
    out(f"{BOLD}{YELLOW}? Which checkout flow should the plan use?{RESET}", .25)
    out(f"  {GREEN}› Hosted Stripe Checkout{RESET}", .25)
    out("    Embedded pricing table", .2)
    out("    Custom payment form", .8)
    ask_prompt()
    out(f"{GREEN}Pi{RESET}  Great — I’ll plan around hosted checkout and the customer portal.\n", .8)
    out(f"{BOLD}Plan: Add Stripe subscriptions{RESET}", .3)
    out("  • Scope: products, checkout session, webhook, customer portal", .35)
    out("  • Approach: env validation → checkout route → webhook handler → tests", .35)
    out("  • Risks: webhook signatures, duplicate events, missing secrets", .35)
    out("  • Done: create/cancel flow works locally and tests pass\n", .9)
    out(f"{BOLD}{YELLOW}? Save this durable plan?{RESET}", .25)
    out(f"  {GREEN}› Approve and select{RESET}", .25)
    out("    Approve", .2)
    out("    Discuss further", .8)
    ask_prompt()
    out(f"{DIM}tool: pi_plan_create(title: Add Stripe subscriptions){RESET}", .7)
    out(f"{GREEN}Pi{RESET}  Saved and selected durable plan.", .55)
    out(f"{DIM}Footer: Plan Selected{RESET}\n", 1.0)
    ask_prompt()
    out(f"{BOLD}# Add Stripe subscriptions{RESET}\n", .25)
    out("Scope: products, checkout session, webhook, customer portal", .25)
    out("Approach: env validation → checkout route → webhook handler → tests", .25)
    out("Risks: webhook signatures, duplicate events, missing secrets", .25)
    out("Completion: create/cancel flow works locally and tests pass\n", .4)
    out(f"{GREEN}Plan first. Clarify decisions. Approve deliberately. Resume with context.{RESET}", 3.0)
if __name__ == '__main__': main()
